line-length = 120
target-version = "py311"

include = [
    "backend/app/**/*.py",
    "examples/**.py"
]

[format]
quote-style = "double"
exclude = []

[lint]
select = [
    "E", "F", "I", "W", "UP", "YTT", "ASYNC", "S", "B", "A", "FA", "PL", "FURB", "RUF", "PERF", "FAST",
    "ASYNC", "C4", "T10", "ISC", "ICN", "G", "INP", "SLOT", "PIE",
]
ignore = ["E501", "B904", "S301", "S608", "S311", "PLR09", "PLR2004", "PLC0415", "RUF005", "RUF012", "S101", "G004", "E402"]
fixable = ["ALL"]


[lint.isort]
force-single-line = true
order-by-type = false
lines-after-imports = 2
case-sensitive = true
required-imports = ["from __future__ import annotations"]
